### ISSUE TITLE
Support for Data migration alone

### ISSUE THREAD

**Issue by surapuramakhil** [techouse/sqlite3-to-mysql#105]
**Is your feature request related to a problem? Please describe.**
I understand that **migration schema from sqlite is a bit tough** provided with the choices available and sometimes if lower sized data type chosen data gets corrupted.

Can we have an option just performing data migration Alone provide schema already exists. 

there are plenty of way schema can be generated
one of them is using backend's ORM's 

**Describe the solution you'd like**
Can we have an option just performing data migration Alone provide schema already exists. 

**Describe alternatives you've considered**
there is only tool for this in FOSS category for migration from sqliteToMysql

**Additional context**

**Comment by techouse** [comment]
This should already work. If you have created all the tables and columns that the tool expects it won't try to make new ones and will only migrate the data.

**Comment by surapuramakhil** [comment]
when I tried this I has messed with schema adding repeated or duplicate indexes. Also there were errors while I am running

I am attaching original schema and modified schema by tool. [schema_diff.zip](https://github.com/techouse/sqlite3-to-mysql/files/14345437/schema_diff.zip) Hope that would give you better answers.

**Comment by surapuramakhil** [comment]
tool output - executed in debug mode in debug mode

```sh
 sqlite3mysql -f ******* -d ******* -u ******** -p -l migration_log --debug

sqlite3mysql version 2.1.7 Copyright (c) 2018-2024 Klemen Tusar
2024-02-20 14:04:55 INFO     Transferring table activity
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 68.76it/s]
2024-02-20 14:04:55 INFO     Adding index to column "trigger_user_id" in table activity
2024-02-20 14:04:55 INFO     Adding index to column "trigger_user_id" in table activity
2024-02-20 14:04:56 WARNING  Duplicate key "IDX_activity_trigger_user_id" in table activity detected! Trying to create new key "IDX_activity_trigger_user_id_1" ...
2024-02-20 14:04:56 INFO     Adding index to column "user_id" in table activity
2024-02-20 14:04:56 INFO     Adding index to column "user_id" in table activity
2024-02-20 14:04:56 WARNING  Duplicate key "IDX_activity_user_id" in table activity detected! Trying to create new key "IDX_activity_user_id_1" ...
2024-02-20 14:04:56 INFO     Adding index to column "object_id" in table activity
2024-02-20 14:04:56 INFO     Adding index to column "object_id" in table activity
2024-02-20 14:04:56 WARNING  Duplicate key "IDX_activity_object_id" in table activity detected! Trying to create new key "IDX_activity_object_id_1" ...
2024-02-20 14:04:56 INFO     Adding index to column "user_id" in table answer
2024-02-20 14:04:56 INFO     Adding index to column "user_id" in table answer
2024-02-20 14:04:56 WARNING  Duplicate key "IDX_answer_user_id" in table answer detected! Trying to create new key "IDX_answer_user_id_1" ...
2024-02-20 14:04:56 INFO     Adding index to column "user_id" in table collection
2024-02-20 14:04:56 INFO     Adding index to column "user_id" in table collection
2024-02-20 14:04:56 WARNING  Duplicate key "IDX_collection_user_id" in table collection detected! Trying to create new key "IDX_collection_user_id_1" ...
2024-02-20 14:04:56 INFO     Adding index to column "user_id" in table collection_group
2024-02-20 14:04:56 INFO     Adding index to column "user_id" in table collection_group
2024-02-20 14:04:56 WARNING  Duplicate key "IDX_collection_group_user_id" in table collection_group detected! Trying to create new key "IDX_collection_group_user_id_1" ...
2024-02-20 14:04:56 INFO     Adding index to column "object_id" in table comment
2024-02-20 14:04:56 INFO     Adding index to column "object_id" in table comment
2024-02-20 14:04:56 WARNING  Duplicate key "IDX_comment_object_id" in table comment detected! Trying to create new key "IDX_comment_object_id_1" ...
2024-02-20 14:04:56 INFO     Transferring table config
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 129/129 [00:00<00:00, 1576.39it/s]
2024-02-20 14:04:56 INFO     Adding unique index to column "key" in table config
2024-02-20 14:04:56 INFO     Adding unique index to column "key" in table config
2024-02-20 14:04:57 ERROR    MySQL failed adding index to column "key" in table config: 1089 (HY000): Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys
Traceback (most recent call last):
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/sqlite3_to_mysql/transporter.py", line 520, in _add_index
    self._mysql_cur.execute(sql)
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/mysql/connector/cursor.py", line 1510, in execute
    res = self._connection.cmd_stmt_execute(
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 74, in wrapper
    return method(cnx, *args, **kwargs)
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/mysql/connector/connection.py", line 1459, in cmd_stmt_execute
    result = self._handle_binary_result(packet)
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/mysql/connector/connection.py", line 1349, in _handle_binary_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1061 (42000): Duplicate key name 'UQE_config_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/akhil/pp-python-env/bin/sqlite3mysql", line 8, in <module>
    sys.exit(cli())
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/sqlite3_to_mysql/cli.py", line 187, in cli
    ).transfer()
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/sqlite3_to_mysql/transporter.py", line 724, in transfer
    self._add_indices(table["name"])
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/sqlite3_to_mysql/transporter.py", line 464, in _add_indices
    self._add_index(
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/sqlite3_to_mysql/transporter.py", line 526, in _add_index
    self._add_index(
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/sqlite3_to_mysql/transporter.py", line 520, in _add_index
    self._mysql_cur.execute(sql)
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/mysql/connector/cursor.py", line 1510, in execute
    res = self._connection.cmd_stmt_execute(
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 74, in wrapper
    return method(cnx, *args, **kwargs)
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/mysql/connector/connection.py", line 1459, in cmd_stmt_execute
    result = self._handle_binary_result(packet)
  File "/root/akhil/pp-python-env/lib/python3.10/site-packages/mysql/connector/connection.py", line 1349, in _handle_binary_result
    raise get_exception(packet)
mysql.connector.errors.DatabaseError: 1089 (HY000): Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys
(pp-python-env) root@400883:
```

Also migration log file generated by command. 
[migration_log.txt](https://github.com/techouse/sqlite3-to-mysql/files/14345559/migration_log.txt)

**Comment by surapuramakhil** [comment]
it mostly refers to adding indexes

**Comment by techouse** [comment]
> it mostly refers to adding indexes

Simply skip the foregin keys or ignore duplicates, just like the readme says

```
-X, --without-foreign-keys      Do not transfer foreign keys.
-W, --ignore-duplicate-keys     Ignore duplicate keys. The default behavior
                                is to create new ones with a numerical
                                suffix, e.g. 'exising_key' ->
                                'existing_key_1'
```

**Comment by surapuramakhil** [comment]
oh gotcha. then as a user i would say this tools requires a learning curve.

it would be nice to have simpler options (as as example -d which me data alone) that would act as wrapper and set internal flags like -X and -W .

thank you I will try it out.

**Comment by techouse** [comment]
> it would be nice to have simpler options (as as example -d which means data transfer alone) that would act as wrapper and set internal flags like -X and -W .

PRs are welcome 🤗
