### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by gerardsyd** [techouse/sqlite3-to-mysql#44]
**Describe the bug**
I'm trying to convert an sqlite file to mysql / MariaDB but I get the following error:
2022-08-09 12:23:45 ERROR    1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-assistant_v2' at line 1

**Expected behaviour**
Conversion to occur without error

**Actual result**
Got error as above
Traceback when running with --debug flag:

Traceback (most recent call last):
  File "/home/gp/.local/bin/sqlite3mysql", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/gp/.local/lib/python3.10/site-packages/sqlite3_to_mysql/cli.py", line 179, in cli
    converter = SQLite3toMySQL(
  File "/home/gp/.local/lib/python3.10/site-packages/sqlite3_to_mysql/transporter.py", line 169, in __init__
    self._mysql.database = self._mysql_database
  File "/home/gp/.local/lib/python3.10/site-packages/mysql/connector/connection.py", line 1136, in database
    self.cmd_query("USE %s" % value)
  File "/home/gp/.local/lib/python3.10/site-packages/mysql/connector/connection.py", line 922, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/gp/.local/lib/python3.10/site-packages/mysql/connector/connection.py", line 732, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-assistant_v2' at line 1

I'm guessing it has something to do with the source file but it is quite large and not sure what the error is trying to say. Any ideas? Thanks!

**Comment by techouse** [comment]
I'll need more information, e.g. the command line you ran and some data (or maybe just the DDL). Without that, I can't help you much.

**Comment by techouse** [comment]
@gerardsyd I had a hunch that that would be the issue. File names are a quite sensitive thing. As a rule of thumb never use any spaces, dashes and non-ASCII characters.
