### ISSUE TITLE
 Character set 'utf8' unsupported

### ISSUE THREAD

**Issue by frli4797** [techouse/sqlite3-to-mysql#47]
Running this under brew on an Intel Mac (OS 12.5.1). Tried with python 3.10 and python 3.7.8 with pyenv. This is driving me crazy.
The database (MariaDB mariadbd (server 10.9.2-MariaDB-1:10.9.2+maria~ubu2204).

Db creation using:
`mysql -e 'CREATE SCHEMA IF NOT EXISTS `homeassistant` DEFAULT CHARACTER SET utf8mb4'`

This is absolutely driving me crazy.

```
sqlite3mysql -f home-assistant_v2.db  -u hassio -d homeassistant -h unraid -E --mysql-password xxx  --debug
2022-08-27 17:10:26 ERROR    Character set 'utf8' unsupported
Traceback (most recent call last):
  File "/usr/local/bin/sqlite3mysql", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlite3_to_mysql/cli.py", line 179, in cli
    converter = SQLite3toMySQL(
  File "/usr/local/lib/python3.9/site-packages/sqlite3_to_mysql/transporter.py", line 155, in __init__
    self._mysql = mysql.connector.connect(
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 287, in connect
    return MySQLConnection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/connection.py", line 137, in __init__
    self.connect(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1095, in connect
    self._open_connection()
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/connection.py", line 544, in _open_connection
    self.set_converter_class(self._converter_class)
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1271, in set_converter_class
    self.converter = convclass(charset_name, self._use_unicode)
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/conversion.py", line 136, in __init__
    MySQLConverterBase.__init__(self, charset, use_unicode, str_fallback)
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/conversion.py", line 59, in __init__
    self.set_charset(charset)
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/conversion.py", line 73, in set_charset
    self.charset_id = CharacterSet.get_charset_info(self.charset)[0]
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/constants.py", line 775, in get_charset_info
    info = cls.get_default_collation(charset)
  File "/usr/local/lib/python3.9/site-packages/mysql/connector/constants.py", line 746, in get_default_collation
    raise ProgrammingError(f"Character set '{charset}' unsupported")
mysql.connector.errors.ProgrammingError: Character set 'utf8' unsupported
```

**Comment by techouse** [comment]
The authors of the MySQL Connector Python [changed the charsets in `v8.0.30`](https://github.com/mysql/mysql-connector-python/commit/c51ba797b7b0f3139fb7b9f4d30d447d68a64d66).

You have 2 options:
1. Downgrade the connector to `v8.0.29` using something like `pip install mysql-connector-python==8.0.29`
2. Wait for me to fix it.

**Comment by techouse** [comment]
Fixed.
