### ISSUE TITLE
Incomprehensible error message: invalid column type

### ISSUE THREAD

**Issue by nise** [techouse/sqlite3-to-mysql#94]
**Describe the bug**
A user converting large table sets needs precice information about the what was going wrong during the conversion. Instead, the program only responds with the type of problem.

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/sqlite3mysql", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/sqlite3_to_mysql/cli.py", line 153, in cli
    SQLite3toMySQL(
  File "/opt/homebrew/lib/python3.9/site-packages/sqlite3_to_mysql/transporter.py", line 651, in transfer
    self._create_table(table["name"], transfer_rowid=transfer_rowid)
  File "/opt/homebrew/lib/python3.9/site-packages/sqlite3_to_mysql/transporter.py", line 321, in _create_table
    column_type: str = self._translate_type_from_sqlite_to_mysql(column["type"])
  File "/opt/homebrew/lib/python3.9/site-packages/sqlite3_to_mysql/transporter.py", line 254, in _translate_type_from_sqlite_to_mysql
    raise ValueError("Invalid column_type!")
ValueError: Invalid column_type!
```

**Expected behaviour**

The names of the columns that are considered invalid.

**Actual result**
What happened instead.

I see just the message but don't get a hint about the origins of the error:
 "Invalid column_type!"

**System Information**
Mac arm64, Python 3.9

```bash
$ sqlite3mysql --version
| software               | version                                             |
|------------------------|-----------------------------------------------------|
| sqlite3-to-mysql       | 2.1.1                                               |
|                        |                                                     |
| Operating System       | Darwin 23.1.0                                       |
| Python                 | CPython 3.9.17                                      |
| MySQL                  | mysql  Ver 8.0.29 for macos11.6 on arm64 (Homebrew) |
| SQLite                 | 3.44.1                                              |
|                        |                                                     |
| click                  | 8.1.3                                               |
| mysql-connector-python | 8.2.0                                               |
| pytimeparse2           | 1.7.1                                               |
| simplejson             | 3.19.2                                              |
| tabulate               | 0.9.0                                               |
| tqdm                   | 4.66.1     
```

```
<paste here>
```

This command is only available on v1.3.6 and greater. Otherwise, please provide some basic information about your system (Python version, operating system, etc.).

**Additional context**

In case of errors please run the same command with `--debug`. This option is only available on v1.4.12 or greater.

**Comment by nise** [comment]
Great. This is really helpful.

**Comment by techouse** [comment]
OK, I'll draft a release then.
